.gitignore
README.md
main.tf
variables.tf

Update readme
Fix elastic_ip_pool to remove errors when null and support multiple tags

update readme and fix elastic_ip_pool block

---

examples/basic_labels_taints.tf
examples/block_device_mapping.tf
examples/scheduling_shutdown_hours.tf
examples/scheduling_tasks.tf
main.tf
outputs.tf
variables.tf

* changed block_device_mappings variable to a list of objects
* ran `terraform fmt` to format terraform code resulting in some quoting and numerous whitespace changes.
* updated block_device_example to use list of objects

Allow multiple block device mappings

---

CHANGELOG.md
main.tf

Make tag key "Name" optional. 
Address user's request in: https://github.com/spotinst/terraform-spotinst-ocean-aws-k8s-vng/pull/8

V0.4.1 - Make tag name optional

---

main.tf
variables.tf

Updated module to support delete_nodes as part of SPOTAUT-12024.

support delete_nodes

---

README.md
examples/basic_labels_taints.tf
examples/block_device_mapping.tf
examples/scheduling_shutdown_hours.tf
examples/scheduling_tasks.tf
variables.tf
versions.tf

- Remove the use of cluster_name
- Update readme and examples

Remove the use of cluster_name

---

README.md
examples/basic/main.tf
main.tf
variables.tf
versions.tf

Added support for 'instance_types_filters'.

Added support for 'instance_types_filters'.

---

CHANGELOG.md

changelog v0.5.0

---

CHANGELOG.md

changelog_0.6.0

---

CHANGELOG.md

Changelog v0.7.0

---

CHANGELOG.md

changelog v0.8.0

---

.terraform-registry

change-owner-request

---

README.md
main.tf
variables.tf

added support for `preferred_od_types`
https://spotinst.atlassian.net/browse/SPOTAUT-19066

added support for `preferred_od_types`

---

CHANGELOG.md

Changelog v0.10.0

---

README.md
main.tf
variables.tf

added support for `draining_timeout` field
https://spotinst.atlassian.net/browse/SPOTAUT-19498

added support for draining_timeout field

---

CHANGELOG.md

V0.11.0 Changelog

---

CHANGELOG.md

Changelog v0.11.1

---

CHANGELOG.md

Changelog v0.12.0

---

README.md

updated controller v2 reference
https://spotinst.atlassian.net/browse/SPOTAUT-19842

updated controller v2 reference

---

CHANGELOG.md

Changelog 0.14.0

---

CHANGELOG.md

Changelog v0.16.0

---

CHANGELOG.md

Changelog v0.17.0

---

CHANGELOG.md

changelog v0.18.0
